networks:
  delivery_network:
    driver: bridge

volumes:
  delivery_db_data:

services:
  postgresdb:
    image: postgres:latest
    container_name: delivery_postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DATASOURCE_DATABASE}
    ports:
      - "5433:5433"
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -h localhost -U ${DATASOURCE_USERNAME} -d ${DATASOURCE_DATABASE}",
      ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - delivery_network
    volumes:
      - delivery_db_data:/var/lib/postgresql/data

  app:
    container_name: delivery_client
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
#      JAVA_OPTS: "-Xms512m -Xmx1024m"
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - delivery_network
